App.Option = DS.Model.extend({
    _id: DS.attr('string'),
    type: DS.attr('string'),
    timestamp: DS.attr('string'),
    strike_price: DS.attr('number'),
    maturity: DS.attr('number'),
    risk_free_rate: DS.attr('number'),
    start_price: DS.attr('number'),
    start_prices: DS.attr('array'),
    volatility: DS.attr('number'),
    volatilities: DS.attr('array'),
    correlations: DS.attr('array'),
    number_of_assets: DS.attr('number'),
    price: DS.attr('number'),
    confidence_interval: DS.attr('array'),
    samples: DS.attr('number'),
    completed: DS.attr('boolean'),
    priced: DS.attr('boolean'),
});

